# Diagora | Frontend - CI
name: Diagora | Frontend - CI

# Controls when the action will run. Triggers the workflow on push or pull request events
# but only for the CI branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Execute the tests
  # Run condition: push or pull request on the CI branch
  tests:
    name: Diagora | Frontend - Tests
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: 19

    - name: Install Dependencies
      run: npm i

    # - name: Run Tests
    #   run: npm run test

    - name: Run Test
      id: tested
      run: |
        echo "No test to execute"
  
  # Build and push the docker image
  # Run condition: push or pull request on the CI branch and tests job is successful
  Docker:
    name: Build and Push Docker
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend_react:latest
  
  # Send a notification on Discord of the triggered error
  # Run condition: push or pull request on the CI branch and tests job is failed
  Discord:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: tests
    if: |
      always() &&
      needs.tests.result == 'failure'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Discord Send Notification
      run: |
        echo "WIP for Discord Notification"
    
        steps:
    - name: Test Step for Discord Action
      uses: Poss111/discord-hook-action@v1.6.12
      with:
          discord-hook-url: 'https://discord.com/api/webhooks/1126047437157576765/ujEXZg_3Ruclp-ZQXDQw2d44JgKaG3lAIN151hnJSgbfeLfGRxQ2rn685Yb_QzMOtdWm'
          title: 'Frontend Action Error'
          message: 'An Error Occured during the Test action.'
          message-color: '16711680'
    - name: Was Job Successful
      run: echo "The job was successful ran > ${{ steps.tested.outputs.successful }}"
